<a href="https://colab.research.google.com/github/kapilpandey09/NLP/blob/main/Word_Embedding_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# NLP: Text Classification using Spacy word Embeddings

# end-to-end fake and real new data


In [ ]:
!pip install spacy
!python -m spacy download en_core_web_lg
import spacy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 1.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
!pip install gensim
import spacy
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')
gl = api.load('glove-twitter-25')

In [ ]:
!pip install matplotlib-venn

In [ ]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate


In [ ]:
nlp = spacy.load("en_core_web_lg")


In [ ]:
import spacy

In [ ]:
!pip install spacy
!pip install -U spacy

In [ ]:
nlp = spacy.load("en_core_web_lg")
doc = nlp("dog cat banana")


In [ ]:
for token in doc:
  print(token.text)

dog
cat
banana


In [ ]:
doc = nlp("dog cat banana tnkin")
for token in doc:
  print(token.text, "vector:", token.has_vector, "OOV:", token.is_oov)

dog vector: True OOV: False
cat vector: True OOV: False
banana vector: True OOV: False
tnkin vector: False OOV: True


In [ ]:
doc[0].vector

array([-4.0176e-01,  3.7057e-01,  2.1281e-02, -3.4125e-01,  4.9538e-02,
        2.9440e-01, -1.7376e-01, -2.7982e-01,  6.7622e-02,  2.1693e+00,
       -6.2691e-01,  2.9106e-01, -6.7270e-01,  2.3319e-01, -3.4264e-01,
        1.8311e-01,  5.0226e-01,  1.0689e+00,  1.4698e-01, -4.5230e-01,
       -4.1827e-01, -1.5967e-01,  2.6748e-01, -4.8867e-01,  3.6462e-01,
       -4.3403e-02, -2.4474e-01, -4.1752e-01,  8.9088e-02, -2.5552e-01,
       -5.5695e-01,  1.2243e-01, -8.3526e-02,  5.5095e-01,  3.6410e-01,
        1.5361e-01,  5.5738e-01, -9.0702e-01, -4.9098e-02,  3.8580e-01,
        3.8000e-01,  1.4425e-01, -2.7221e-01, -3.7016e-01, -1.2904e-01,
       -1.5085e-01, -3.8076e-01,  4.9583e-02,  1.2755e-01, -8.2788e-02,
        1.4339e-01,  3.2537e-01,  2.7226e-01,  4.3632e-01, -3.1769e-01,
        7.9405e-01,  2.6529e-01,  1.0135e-01, -3.3279e-01,  4.3117e-01,
        1.6687e-01,  1.0729e-01,  8.9418e-02,  2.8635e-01,  4.0117e-01,
       -3.9222e-01,  4.5217e-01,  1.3521e-01, -2.8878e-01, -2.28

In [ ]:
doc[0].vector.shape

(300,)

In [ ]:
base_token = nlp("sandwich")
base_token.vector.shape

(300,)

In [ ]:
doc = nlp("bread sandwich burger car tiger human wheat")
for token in doc:
    print(f"{token.text} < - > {base_token.text}: , : {token.similarity(base_token)}")

bread < - > sandwich: , : 0.6874560117721558
sandwich < - > sandwich: , : 1.0
burger < - > sandwich: , : 0.767081618309021
car < - > sandwich: , : 0.1664874404668808
tiger < - > sandwich: , : 0.1713561713695526
human < - > sandwich: , : 0.14466442167758942
wheat < - > sandwich: , : 0.377204567193985


In [37]:
def similar_words(base_word, word_to_compare):
    base_token = nlp(base_word)
    doc = nlp(word_to_compare)
    for token in doc:
      print(f"{token.test} < - >{base_token.text} : ", token.similarity(base_token))

In [39]:
def similar_words(base_word, word_to_compare):
    base_token = nlp(base_word)
    doc = nlp(word_to_compare)
    for token in doc:
      print(f"{token.text} < - >{base_token.text} : ", token.similarity(base_token))


apple < - >iphone :  0.6339781284332275
sumung < - >iphone :  0.0
iphone < - >iphone :  1.0
dog < - >iphone :  0.1743103712797165
cat < - >iphone :  0.21171651780605316
banana < - >iphone :  0.19600526988506317


/tmp/ipython-input-2673459893.py:5: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  print(f"{token.text} < - >{base_token.text} : ", token.similarity(base_token))


In [40]:
similar_words("iphone", "apple sumung iphone dog cat banana")

apple < - >iphone :  0.6339781284332275
sumung < - >iphone :  0.0
iphone < - >iphone :  1.0
dog < - >iphone :  0.1743103712797165
cat < - >iphone :  0.21171651780605316
banana < - >iphone :  0.19600526988506317


/tmp/ipython-input-2673459893.py:5: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  print(f"{token.text} < - >{base_token.text} : ", token.similarity(base_token))


In [43]:
from sklearn.metrics.pairwise import cosine_similarity
# cosine_similarity([result], [queen])

france = nlp.vocab['france'].vector
paris = nlp.vocab['paris'].vector
london = nlp.vocab['london'].vector
berlin = nlp.vocab['berlin'].vector
cosine_similarity([france - paris + london], [berlin])


array([[0.45168123]], dtype=float32)

In [44]:
# NLP: Text Classification using spacy word Embeddings
# fakeand real news data

In [45]:
import pandas as pd
import numpy as np


In [47]:
df = pd.read_csv("/content/sample_data/Fake.csv", engine='python', on_bad_lines='skip')

In [50]:
df.tail(10)

title  \
393   OOPS: Trump Forgets That He’s A Twitter Obses...   
394   Reporter Destroys Trump’s Homeland Security A...   
395   A Florida Pizza Hut To Irma-Fleeing Employees...   
396   Never Forget: Donald Trump Bragged About Havi...   
397   Fox News Just Compared Slave Owners To 9/11 V...   
398   Trump Praises Coast Guard’s Hurricane Relief ...   
399   Florida GOP Official Tried To Murder A Teen W...   
400   ‘Shoot At Hurricane Irma’ Facebook Event Take...   
401   WATCH: Black Driver Bravely Shames Cop Who Dr...   
402   Trump Junior TOTALLY Staged This Awkward Phot...   

                                                  text subject  \
393  Donald Trump is a complainer, but he really on...    News   
394  The Trump administration has been getting abso...    News   
395  Residents in Florida who work at a Pizza Hut w...    News   
396  I ll bet if you go to your kitchen and look at...    News   
397  Nobody can accuse Fox News of being sane most ...    News   
398  Leave it to Donald Trump to disrespect both th...    News   
399  Back in May, Republicans in Broward County ele...    News   
400  A Facebook event called  Shoot At Hurricane Ir...    News   
401  When you are Black in America, getting pulled ...    News   
402  Last week, Donald Trump Junior became a new fo...    News   

                   date  
393  September 12, 2017  
394  September 11, 2017  
395  September 11, 2017  
396  September 11, 2017  
397  September 11, 2017  
398  September 10, 2017  
399  September 10, 2017  
400  September 10, 2017  
401  September 10, 2017  
402  September 10, 2017

In [54]:
df = pd.read_csv("/content/sample_data/True.csv",engine='python', on_bad_lines='skip')

In [55]:
df

title  \
0    As U.S. budget fight looms, Republicans flip t...   
1    U.S. military to accept transgender recruits o...   
2    Senior U.S. Republican senator: 'Let Mr. Muell...   
3    FBI Russia probe helped by Australian diplomat...   
4    Trump wants Postal Service to charge 'much mor...   
..                                                 ...   
400  Kushner told Flynn to contact Russians last ye...   
401  House ethics panel launches wide-ranging probe...   
402  Republican Senator Daines says he will support...   
403  Senate Republicans have 50 votes to pass tax b...   
404  Republicans have the votes to pass tax bill in...   

                                                  text       subject  \
0    WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1    WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2    WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3    WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4    SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
..                                                 ...           ...   
400  WASHINGTON (Reuters) - Jared Kushner, Presiden...  politicsNews   
401  WASHINGTON (Reuters) - The U.S. House of Repre...  politicsNews   
402  WASHINGTON (Reuters) - Republican U.S. Senator...  politicsNews   
403  WASHINGTON (Reuters) - The No. 2 U.S. Senate R...  politicsNews   
404  WASHINGTON (Reuters) - U.S. Senate Republican ...  politicsNews   

                   date  
0    December 31, 2017   
1    December 29, 2017   
2    December 31, 2017   
3    December 30, 2017   
4    December 29, 2017   
..                  ...  
400   December 1, 2017   
401   December 1, 2017   
402   December 1, 2017   
403   December 1, 2017   
404   December 1, 2017   

[405 rows x 4 columns]

In [57]:
df = pd.read_csv("/content/sample_data/news.csv", engine='python', on_bad_lines='skip')

In [61]:
df.tail(10)

Unnamed: 0                                              title  \
393        3106  Miracles Man: Metaxas Vs. Closed Minds And A C...   
394        6804        Obamacare Premiums Spike an Average of 25%!   
395        5352  Collective Consciousness – The Individual is Gone   
396        2339      Obama on gun control: His emotional evolution   
397        7771  What Scientists Found Inside This 800-Year-Old...   
398        2422  The Clock Is Ticking And Republicans Still Hav...   
399        1597         Trump treads on tradition in New Hampshire   
400        4261  GOP presidential candidates hammer on 'top sec...   
401        2640  Cleveland, Justice Department Reach Policing Deal   
402       10454  Physicists Say Consciousness Should Be Conside...   

                                                  text label  
393  Last Christmas, Christian apologist, Eric Meta...  REAL  
394  Print \nSome worrisome news is breaking across...  FAKE  
395  Waking Times \n“In the middle of all the brain...  FAKE  
396  But on one issue -- guns -- President Barack O...  REAL  
397  Share on Facebook In 2008, on a dig in the Fir...  FAKE  
398  Republicans keep saying they’ll be ready to ac...  REAL  
399  Killing Obama administration rules, dismantlin...  REAL  
400  The Republican presidential candidates are sei...  REAL  
401  Cleveland has reached a settlement with the De...  REAL  
402  advertisement - learn more It’s been more than...  FAKE

In [62]:
df.value_counts('label')

label
REAL    213
FAKE    190
Name: count, dtype: int64

In [63]:
print(df.shape)

(403, 4)


In [64]:
# check imbalance in data set
# checkthe distribution of data in our dataset
df['label'].value_counts()

label
REAL    213
FAKE    190
Name: count, dtype: int64

In [71]:
df['label_num'] = df['label'].map({'FAKE':0, 'REAL':1})

In [72]:
print(df.head(10))

   Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   
5        6903                                        Tehran, USA   
6        7341  Girl Horrified At What She Watches Boyfriend D...   
7          95                  ‘Britain’s Schindler’ Dies at 106   
8        4869  Fact check: Trump and Clinton at the 'commande...   
9        2909  Iran reportedly makes new push for uranium con...   

                                                text label  label_num  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0  
2  U.S. Secretary of State John F. 

In [73]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  label_num  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL          1  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE          0  
4  It's primary day in New York and front-runners...  REAL          1

In [74]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [75]:
# convert text to vector

df['vector'] = df['text'].apply(lambda x: nlp(x).vector)


In [76]:
len(df)

403

In [77]:
df

Unnamed: 0                                              title  \
0          8476                       You Can Smell Hillary’s Fear   
1         10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2          3608        Kerry to go to Paris in gesture of sympathy   
3         10142  Bernie supporters on Twitter erupt in anger ag...   
4           875   The Battle of New York: Why This Primary Matters   
..          ...                                                ...   
398        2422  The Clock Is Ticking And Republicans Still Hav...   
399        1597         Trump treads on tradition in New Hampshire   
400        4261  GOP presidential candidates hammer on 'top sec...   
401        2640  Cleveland, Justice Department Reach Policing Deal   
402       10454  Physicists Say Consciousness Should Be Conside...   

                                                  text label  label_num  \
0    Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0   
1    Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0   
2    U.S. Secretary of State John F. Kerry said Mon...  REAL          1   
3    — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE          0   
4    It's primary day in New York and front-runners...  REAL          1   
..                                                 ...   ...        ...   
398  Republicans keep saying they’ll be ready to ac...  REAL          1   
399  Killing Obama administration rules, dismantlin...  REAL          1   
400  The Republican presidential candidates are sei...  REAL          1   
401  Cleveland has reached a settlement with the De...  REAL          1   
402  advertisement - learn more It’s been more than...  FAKE          0   

                                                vector  
0    [-0.06343732, 0.11896122, -0.067684345, -0.018...  
1    [-0.017111547, 0.13953958, -0.05576232, 0.0063...  
2    [-0.018148802, 0.17694649, -0.024513047, -0.04...  
3    [-0.054569427, 0.14917314, 0.0107977595, -0.00...  
4    [-0.020318953, 0.16901688, -0.041723646, -0.06...  
..                                                 ...  
398  [-0.05901427, 0.15097924, -0.08229574, -0.0288...  
399  [-0.07777476, 0.10837752, -0.066752374, 0.0355...  
400  [-0.05793606, 0.16552022, -0.04834549, -0.0299...  
401  [-0.048130736, 0.16686603, -0.046861954, -0.03...  
402  [-0.04616489, 0.1622819, -0.119340956, -0.0151...  

[403 rows x 6 columns]

In [86]:
doc = nlp("dog cat ")
doc.vector
len(doc)

2

In [87]:
len(doc.vector)

300

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.vector.values, df.label_num, test_size=0.2, random_state=42)

In [89]:
X_train.shape

(322,)

In [90]:
X_test.shape

(81,)

In [91]:
X_train_stack = np.stack(X_train)
X_test_stack = np.stack(X_test)

In [93]:
print(X_train_stack.shape)
print(X_test_stack.shape)

(322, 300)
(81, 300)


In [95]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_stack_sc = scaler.fit_transform(X_train_stack)
X_test_stack_sc = scaler.transform(X_test_stack)


model.fit(X_train_stack_sc, y_train)

MultinomialNB()

In [96]:
y_pred = model.predict(X_test_stack_sc)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1])

In [97]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8024691358024691

In [98]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.71      0.76        35
           1       0.80      0.87      0.83        46

    accuracy                           0.80        81
   macro avg       0.80      0.79      0.80        81
weighted avg       0.80      0.80      0.80        81



In [99]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[25, 10],
       [ 6, 40]])